info:
    version: ""
    title: data_source_huaweicloud_apig_api_associated_applications
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/app-auths/binded-apps:
        GET:
            tag: APIG
