info:
    version: ""
    title: data_source_huaweicloud_rds_pg_plugin_parameter_values
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: RDS
paths:
    /v3/{project_id}/instances/{instance_id}/parameter/{name}:
        GET:
            tag: RDS
