info:
    version: ""
    title: data_source_huaweicloud_fgs_applications
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: FunctionGraph
paths:
    /v2/{project_id}/fgs/applications:
        GET:
            tag: FunctionGraph
