info:
    version: ""
    title: data_source_huaweicloud_apig_application_acl
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/apps/{app_id}/app-acl:
        GET:
            tag: APIG
