info:
    version: ""
    title: data_source_huaweicloud_cae_environments
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CAE
paths:
    /v1/{project_id}/cae/environments:
        GET:
            tag: CAE
