info:
    version: ""
    title: data_source_huaweicloud_cc_connection_routes
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CC
paths:
    /v3/{domain_id}/ccaas/cloud-connection-routes:
        GET:
            tag: CC
