info:
    version: ""
    title: data_source_huaweicloud_er_available_routes
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: ER
paths:
    /v3/{project_id}/enterprise-router/route-tables/{route_table_id}/routes:
        GET:
            tag: ER
