info:
    version: ""
    title: resource_huaweicloud_css_es_loadbalancer_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CSS
paths:
    /v1.0/{project_id}/clusters/{cluster_id}/es-listeners:
        GET:
            tag: CSS
        POST:
            tag: CSS
    /v1.0/{project_id}/clusters/{cluster_id}/es-listeners/{listener_id}:
        PUT:
            tag: CSS
    /v1.0/{project_id}/clusters/{cluster_id}/loadbalancers/es-switch:
        POST:
            tag: CSS
