info:
    version: ""
    title: resource_huaweicloud_organizations_policy_dry_run_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Organizations
paths:
    /v1/organizations/dry-run-config:
        GET:
            tag: Organizations
        POST:
            tag: Organizations
