info:
    title: resource_huaweicloud_secmaster_playbook_rule
    description: Manages a SecMaster playbook resource within HuaweiCloud.
host: myhuaweicloud.com
tags:
    - name: SecMaster
servers:
    - url: https://secmaster.cn-east-3.myhuaweicloud.com
paths:
    /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/rules:
        POST:
            tag: SecMaster
            operationId: CreatePlaybookRule
            x-ref-api: POST /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/rules
    /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/rules/{id}:
        DELETE:
            tag: SecMaster
            operationId: DeletePlaybookRule
            x-ref-api: DELETE /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/rules/{id}
        GET:
            tag: SecMaster
            operationId: GetPlaybookRule
            x-ref-api: GET /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/rules/{id}
        PUT:
            tag: SecMaster
            operationId: UpdatePlaybookRule
            x-ref-api: PUT /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/rules/{id}
