info:
    title: resource_huaweicloud_secmaster_playbook_action
    description: Manages a SecMaster playbook action resource within HuaweiCloud.
host: myhuaweicloud.com
tags:
    - name: SecMaster
servers:
    - url: https://secmaster.cn-east-3.myhuaweicloud.com
paths:
    /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/actions:
        GET:
            tag: SecMaster
            operationId: GetPlaybookAction
            x-ref-api: GET /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/actions
        POST:
            tag: SecMaster
            operationId: CreatePlaybookAction
            x-ref-api: POST /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/actions
    /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/actions/{id}:
        DELETE:
            tag: SecMaster
            operationId: DeletePlaybookAction
            x-ref-api: DELETE /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/actions/{id}
        PUT:
            tag: SecMaster
            operationId: UpdatePlaybookAction
            x-ref-api: PUT /v1/{project_id}/workspaces/{workspace_id}/soc/playbooks/versions/{version_id}/actions/{id}
