info:
    version: ""
    title: resource_huaweicloud_apig_application_quota
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/app-quotas:
        POST:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instance_id}/app-quotas/{app_quota_id}:
        DELETE:
            tag: APIG
        GET:
            tag: APIG
        PUT:
            tag: APIG
